### ISSUE TITLE
Where is the sum operation of KV?

### ISSUE THREAD

**Issue by Yogurt928** [idiap/fast-transformers#82]
Code file: fast_transformers/attention/linear_attention.py
Line 72: KV = torch.einsum("nshd,nshm->nhmd", K, values)
Line 78: V = torch.einsum("nlhd,nhmd,nlh->nlhm", Q, KV, Z)

The equation in paper:
![image](https://user-images.githubusercontent.com/15760208/113394330-9bb5ec80-93ca-11eb-9bb1-6aa65dcf9442.png)

Where is the sum operation of KV in the code?

Thanks.

**Comment by angeloskath** [comment]
Hi,

The summation is performed by einsum in line 72. The index `j` in the equation corresponds to `s` in einsum and it is clear that `s` is the one einsum sums over.

The reason for using einsum instead of multiplication and summation is that it is faster since the large matrix does not need to ever be computed and kept in memory.

Best,
Angelos

**Comment by Yogurt928** [comment]
Can I explain the transformation process as following steps ?
1.      
      nshd -> nhds 
     nshm ->  nhsm
2.    nhds x nhsm = nhdm -> nhmd

**Comment by angeloskath** [comment]
Yes of course. It is probably what is happening under the hood. Permute and matrix multiply.

Since it is clear, I will close the issue. Feel free to reopen it in case you have further questions.

Cheers,
Angelos
