### ISSUE TITLE
[FAVOR & friends] Orthogonal random matrix not uniformly drawn

### ISSUE THREAD

**Issue by blefaudeux** [idiap/fast-transformers#87]
Hey there, thanks for the repo to begin with, excellent IMO ! Just a quick question with respect to the orthogonal random matrices, generated with a q,r decomposition from a uniformly random matrix to begin with: it has been shown not to be uniform actually, since the q,r decomposition is not unique, and the decomposition algorithms are biased towards numerical stability. (it's better explained in 
```Mezzadri, F. (2006). How to generate random matrices from the classical compact groups. http://arxiv.org/abs/math-ph/0609050```)

A density plot of the eigen values in the complex plane, from the draw random matrices, is attached to better illustrate the problem. _I was wondering whether it was something you knew, and whether it was an issue in practice. The original Jax implementation does the same, so I'm left wondering whether this should be considered as part of the method (the paper does not mention this twist though)._

Note that an improvement can be reached by returning `Q @ torch.diag(torch.sign(torch.diag(R)))`, not perfect but better distributed. Thanks !

![orf_qr_kde](https://user-images.githubusercontent.com/3072861/116277671-8ff3e680-a73a-11eb-8ada-4e857b0a9739.png)

**Comment by blefaudeux** [comment]
cc @fmassa

**Comment by angeloskath** [comment]
Wow, nice!

It was not something I knew tbh. My first reaction is it doesn't matter in practice since these orthogonal matrices do improve significantly the approximation for random Fourier features. You can check that if you edit the tests in https://github.com/idiap/fast-transformers/blob/master/tests/feature_maps/test_fourier_features.py and print the approximation errors depending on `orthogonal=True` vs `orthogonal=False`.

However, if there is any improvement (in terms of RFF approximation) when using the sign of the eigenvalues of R then we could definitely add this as I am sure it is a negligible hit in performance. Feel free to run some tests if you want and do a PR. If however there is no improvement I believe the best we could do is link to the paper in the [function docstring](https://github.com/idiap/fast-transformers/blob/c985bc7d926bb14b9b82d3772404f95f554f5693/fast_transformers/feature_maps/fourier_features.py#L19) and let people know if they care for this kinds of things.

Thanks for the great issue :-) !
Angelos

P.S.: I did not read the linked paper fully although it does seem interesting.
P.P.S.: Thanks for liking the library.

**Comment by blefaudeux** [comment]
I'll check to see if I can get a measurable difference, my guess is that it would make the random features a little more accurate _per number of features_, but that it may not change much in the grand scheme of things. If measurable I can certainly put up a PR
